In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
auto_df = pd.read_csv(r"C:\Users\rupal\OneDrive\Desktop\practice\flask_practice\autos_dataset.csv")
auto_df

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19     3.4              10.0        102   
4            136         mpfi  3.19     3.4               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01     3.4              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

In [4]:
auto_df.head().T

0            1            2      3      4
symboling                    3            3            1      2      2
normalized-losses            ?            ?            ?    164    164
make               alfa-romero  alfa-romero  alfa-romero   audi   audi
fuel-type                  gas          gas          gas    gas    gas
aspiration                 std          std          std    std    std
num-of-doors               two          two          two   four   four
body-style         convertible  convertible    hatchback  sedan  sedan
drive-wheels               rwd          rwd          rwd    fwd    4wd
engine-location          front        front        front  front  front
wheel-base                88.6         88.6         94.5   99.8   99.4
length                   168.8        168.8        171.2  176.6  176.6
width                     64.1         64.1         65.5   66.2   66.4
height                    48.8         48.8         52.4   54.3   54.3
curb-weight               2548         2548         2823   2337   2824
engine-type               dohc         dohc         ohcv    ohc    ohc
num-of-cylinders          four         four          six   four   five
engine-size                130          130          152    109    136
fuel-system               mpfi         mpfi         mpfi   mpfi   mpfi
bore                      3.47         3.47         2.68   3.19   3.19
stroke                    2.68         2.68         3.47    3.4    3.4
compression-ratio          9.0          9.0          9.0   10.0    8.0
horsepower                 111          111          154    102    115
peak-rpm                  5000         5000         5000   5500   5500
city-mpg                    21           21           19     24     18
highway-mpg                 27           27           26     30     22
price                    13495        16500        16500  13950  17450

In [6]:
auto_df = auto_df.drop(["symboling","normalized-losses","make","peak-rpm","horsepower","compression-ratio","stroke","bore","fuel-system",
                        "num-of-cylinders","engine-type","height","width","length","engine-location","drive-wheels","body-style","aspiration",
                       "num-of-doors","fuel-type"],axis=1) 
auto_df

wheel-base  curb-weight  engine-size  city-mpg  highway-mpg  price
0          88.6         2548          130        21           27  13495
1          88.6         2548          130        21           27  16500
2          94.5         2823          152        19           26  16500
3          99.8         2337          109        24           30  13950
4          99.4         2824          136        18           22  17450
..          ...          ...          ...       ...          ...    ...
200       109.1         2952          141        23           28  16845
201       109.1         3049          141        19           25  19045
202       109.1         3012          173        18           23  21485
203       109.1         3217          145        26           27  22470
204       109.1         3062          141        19           25  22625

[205 rows x 6 columns]

In [7]:
auto_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   wheel-base   205 non-null    float64
 1   curb-weight  205 non-null    int64  
 2   engine-size  205 non-null    int64  
 3   city-mpg     205 non-null    int64  
 4   highway-mpg  205 non-null    int64  
 5   price        205 non-null    object 
dtypes: float64(1), int64(4), object(1)
memory usage: 9.7+ KB


In [9]:
auto_df["wheel-base"].unique()

array([ 88.6,  94.5,  99.8,  99.4, 105.8,  99.5, 101.2, 103.5, 110. ,
        88.4,  93.7, 103.3,  95.9,  86.6,  96.5,  94.3,  96. , 113. ,
       102. ,  93.1,  95.3,  98.8, 104.9, 106.7, 115.6,  96.6, 120.9,
       112. , 102.7,  93. ,  96.3,  95.1,  97.2, 100.4,  91.3,  99.2,
       107.9, 114.2, 108. ,  89.5,  98.4,  96.1,  99.1,  93.3,  97. ,
        96.9,  95.7, 102.4, 102.9, 104.5,  97.3, 104.3, 109.1])

In [10]:
auto_df["curb-weight"].unique()

array([2548, 2823, 2337, 2824, 2507, 2844, 2954, 3086, 3053, 2395, 2710,
       2765, 3055, 3230, 3380, 3505, 1488, 1874, 1909, 1876, 2128, 1967,
       1989, 2191, 2535, 2811, 1713, 1819, 1837, 1940, 1956, 2010, 2024,
       2236, 2289, 2304, 2372, 2465, 2293, 2734, 4066, 3950, 1890, 1900,
       1905, 1945, 1950, 2380, 2385, 2500, 2410, 2443, 2425, 2670, 2700,
       3515, 3750, 3495, 3770, 3740, 3685, 3900, 3715, 2910, 1918, 1944,
       2004, 2145, 2370, 2328, 2833, 2921, 2926, 2365, 2405, 2403, 1889,
       2017, 1938, 1951, 2028, 1971, 2037, 2008, 2324, 2302, 3095, 3296,
       3060, 3071, 3139, 3020, 3197, 3430, 3075, 3252, 3285, 3485, 3130,
       2818, 2778, 2756, 2800, 3366, 2579, 2460, 2658, 2695, 2707, 2758,
       2808, 2847, 2050, 2120, 2240, 2190, 2340, 2510, 2290, 2455, 2420,
       2650, 1985, 2040, 2015, 2280, 3110, 2081, 2109, 2275, 2094, 2122,
       2140, 2169, 2204, 2265, 2300, 2540, 2536, 2551, 2679, 2714, 2975,
       2326, 2480, 2414, 2458, 2976, 3016, 3131, 31

In [11]:
auto_df["engine-size"].unique()

array([130, 152, 109, 136, 131, 108, 164, 209,  61,  90,  98, 122, 156,
        92,  79, 110, 111, 119, 258, 326,  91,  70,  80, 140, 134, 183,
       234, 308, 304,  97, 103, 120, 181, 151, 194, 203, 132, 121, 146,
       171, 161, 141, 173, 145], dtype=int64)

In [12]:
auto_df["city-mpg"].unique()

array([21, 19, 24, 18, 17, 16, 23, 20, 15, 47, 38, 37, 31, 49, 30, 27, 25,
       13, 26, 36, 22, 14, 45, 28, 32, 35, 34, 29, 33], dtype=int64)

In [13]:
auto_df["highway-mpg"].unique()

array([27, 26, 30, 22, 25, 20, 29, 28, 53, 43, 41, 38, 24, 54, 42, 34, 33,
       31, 19, 17, 23, 32, 39, 18, 16, 37, 50, 36, 47, 46], dtype=int64)

In [22]:
auto_df["price"].unique()

array([13495.        , 16500.        , 13950.        , 17450.        ,
       15250.        , 17710.        , 18920.        , 23875.        ,
       13207.12935323, 16430.        , 16925.        , 20970.        ,
       21105.        , 24565.        , 30760.        , 41315.        ,
       36880.        ,  5151.        ,  6295.        ,  6575.        ,
        5572.        ,  6377.        ,  7957.        ,  6229.        ,
        6692.        ,  7609.        ,  8558.        ,  8921.        ,
       12964.        ,  6479.        ,  6855.        ,  5399.        ,
        6529.        ,  7129.        ,  7295.        ,  7895.        ,
        9095.        ,  8845.        , 10295.        , 12945.        ,
       10345.        ,  6785.        , 11048.        , 32250.        ,
       35550.        , 36000.        ,  5195.        ,  6095.        ,
        6795.        ,  6695.        ,  7395.        , 10945.        ,
       11845.        , 13645.        , 15645.        ,  8495.        ,
      

In [21]:
auto_df.replace({'?':np.nan}, inplace=True)
auto_df['price'] = auto_df['price'].astype(float)
auto_df['price'] = auto_df['price'].fillna(auto_df['price'].mean())

In [40]:
auto_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   wheelbase   205 non-null    float64
 1   curbweight  205 non-null    int64  
 2   enginesize  205 non-null    int64  
 3   citympg     205 non-null    int64  
 4   highwaympg  205 non-null    int64  
 5   price       205 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 9.7 KB


In [39]:
auto_df.rename({"curb-weight":"curbweight","engine-size":"enginesize","city-mpg":"citympg","highway-mpg":"highwaympg"},axis=1,inplace=True)

In [41]:
x = auto_df.drop(["price"],axis=1)
y = auto_df["price"]

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [43]:
x_train

wheelbase  curbweight  enginesize  citympg  highwaympg
71       115.6        3740         234       16          18
9         99.5        3053         131       16          22
118       93.7        1918          90       37          41
174      102.4        2480         110       30          33
146       97.0        2290         108       28          32
..         ...         ...         ...      ...         ...
43        94.3        2337         111       24          29
22        93.7        1876          90       31          38
72        96.6        3685         234       16          18
15       103.5        3230         209       16          22
168       98.4        2536         146       24          30

[164 rows x 5 columns]

In [44]:
def model_building(algo, x, y):
    model = algo
    model.fit(x, y)
    return model

linear_reg = model_building(LinearRegression(), x_train, y_train)
linear_reg

LinearRegression()

In [45]:
y_pred = linear_reg.predict(x_test)

In [52]:
def evaluation(model, ind_var, y_act):
    pred = model.predict(ind_var)
    
    mse = mean_squared_error(y_act, pred)
    print('MSE:', mse)

    rmse = np.sqrt(mse)
    print('RMSE:', rmse)

    mae = mean_absolute_error(y_act, pred)
    print('MAE:', mae)

    r_squared = r2_score(y_act, pred)
    print('R2_Score:',r_squared)
    
print('Test Data Evaluation'.center(50, '*'))
evaluation(linear_reg, x_test, y_test)

print()

print('Train Data Evaluation'.center(50, '*'))
evaluation(linear_reg, x_train, y_train)

***************Test Data Evaluation***************
MSE: 16443301.432620734
RMSE: 4055.0340852600407
MAE: 2960.479218251453
R2_Score: 0.5235269600776253

**************Train Data Evaluation***************
MSE: 13548640.730896741
RMSE: 3680.847827728924
MAE: 2562.659610991817
R2_Score: 0.8018627104395208


In [47]:
x.head(1).T

0
wheelbase     88.6
curbweight  2548.0
enginesize   130.0
citympg       21.0
highwaympg    27.0

In [48]:
wheelbase = 90
curbweight = 3000
enginesize = 150
citympg = 25
highwaympg = 27

#charges = ?

In [50]:
test_array = np.array([wheelbase,curbweight,enginesize,citympg,highwaympg], ndmin = 2)
test_array

array([[  90, 3000,  150,   25,   27]])

In [53]:
linear_reg.predict(test_array)

C:\Users\rupal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([17240.21306955])

In [54]:
print(x.columns)
len(x.columns)

Index(['wheelbase', 'curbweight', 'enginesize', 'citympg', 'highwaympg'], dtype='object')


5

In [55]:
x.shape[1]

5

In [56]:
project_data = {"columns":list(x.columns)}
project_data

{'columns': ['wheelbase', 'curbweight', 'enginesize', 'citympg', 'highwaympg']}

In [57]:
test_array = np.zeros(x.shape[1])
test_array[0] = wheelbase
test_array[1] = curbweight
test_array[2] = enginesize
test_array[3] = citympg
test_array[4] = highwaympg
test_array

array([  90., 3000.,  150.,   25.,   27.])

In [60]:
result = np.around(linear_reg.predict([test_array])[0],2)
print(f"Prediction for automobile : RS.{result}")

Prediction for automobile : RS.17240.21


C:\Users\rupal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [61]:
import json
import pickle

In [62]:
with open("auto.pkl","wb") as f:
    pickle.dump(linear_reg,f)

In [63]:
with open("Project_data.json","w") as f:
    json.dump(project_data,f)